#!/usr/bin/env python3
"""
Condor Fun4All Job Completion Monitor

Monitors a directory containing Condor job output/stdout files (such as those
generated by genFun4All*.sh scripts). Periodically checks that all log files in
the directory have reached the final finish message (e.g. "Finished" or
"Finished successfully"). Once all jobs have completed, sends an email
notification to the user and exits.

Usage Examples:
    # Positional arguments: <dir> <interval> <email>
    python scripts/condor/monitor_jobs.py /sphenix/u/user/scratch/f4a/stdout 60 user@bnl.gov

    # Named arguments with time units (e.g. 30s, 5m, 1h):
    python scripts/condor/monitor_jobs.py --dir /sphenix/u/user/scratch/f4a --interval 5m --email user@bnl.gov

    # Specify expected number of jobs (if not auto-detected from jobs.list):
    python scripts/condor/monitor_jobs.py -d scratch/f4a/stdout -i 2m -e user@bnl.gov -n 120

    # Test email sending before starting monitoring:
    python scripts/condor/monitor_jobs.py --test-email --email user@bnl.gov

    # Check directory status once and exit (exit code 0 if all done, 1 if pending):
    python scripts/condor/monitor_jobs.py /sphenix/u/user/scratch/f4a/stdout --run-once
"""

# pylint: disable=too-many-arguments,too-many-branches,too-many-return-statements,too-many-locals

import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
import email.utils
from email.mime.text import MIMEText
import fnmatch
import os
from pathlib import Path
import re
import shutil
import smtplib
import socket
import subprocess
import sys
import time

# Ensure stdout and stderr are line-buffered for real-time tailing when redirected via nohup
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(line_buffering=True)

DEFAULT_FINISH_PATTERN = r"^\s*Finished(\s+successfully.*)?\s*$"
DEFAULT_ERROR_PATTERN = (
    r"(Error:\s*ROOT macro crashed"
    r"|Error:\s*cp failed permanently"
    r"|condor scratch NOT set"
    r"|Segmentation fault"
    r"|Fatal in <"
    r"|Bus error"
    r"|\bAborted\b)"
)
ERROR_BYTE_TOKENS = (
    b"Error:",
    b"ROOT macro crashed",
    b"cp failed permanently",
    b"condor scratch NOT set",
    b"Segmentation fault",
    b"Fatal in <",
    b"Bus error",
    b"Aborted",
)


def parse_interval(val: str) -> float:
    """Parses time intervals like '60', '30s', '5m', '1h', '0.5h' into seconds."""
    val = val.strip()
    match = re.match(r"^([0-9]+(?:\.[0-9]+)?)\s*([a-zA-Z]*)$", val)
    if not match:
        raise ValueError(
            f"Invalid interval format: '{val}'. Expected number of seconds (e.g. 60) or with unit (e.g. '30s', '5m', '1h')"
        )
    num = float(match.group(1))
    unit = match.group(2).lower()
    if unit in ("", "s", "sec", "second", "seconds"):
        return num
    if unit in ("m", "min", "minute", "minutes"):
        return num * 60.0
    if unit in ("h", "hr", "hour", "hours"):
        return num * 3600.0
    if unit in ("d", "day", "days"):
        return num * 86400.0
    raise ValueError(f"Unknown time unit '{unit}' in interval: '{val}'")


def format_duration(seconds: float) -> str:
    """Formats seconds into human-readable duration like '1h 23m 45s'."""
    sec_int = int(seconds)
    hours, remainder = divmod(sec_int, 3600)
    minutes, secs = divmod(remainder, 60)
    parts = []
    if hours > 0:
        parts.append(f"{hours}h")
    if minutes > 0 or hours > 0:
        parts.append(f"{minutes}m")
    parts.append(f"{secs}s")
    return " ".join(parts)


def send_email(
    to_email: str,
    subject: str,
    body: str,
    sender: str | None = None,
    smtp_server: str | None = None,
    smtp_port: int | None = None,
    smtp_user: str | None = None,
    smtp_password: str | None = None,
    smtp_tls: bool = False,
    smtp_ssl: bool = False,
    mail_cmd: str | None = None,
) -> tuple[bool, str]:
    """
    Sends an email using the best available mechanism:
    1. Specified mail command (e.g. mail, mailx, sendmail)
    2. Configured SMTP server
    3. Auto-detected local mail command (mailx, mail, /usr/sbin/sendmail)
    4. Localhost SMTP (localhost:25)

    Returns:
        (success, message)
    """
    hostname = socket.gethostname()
    if not sender:
        username = os.environ.get("USER", "root")
        sender = f"{username}@{hostname}"

    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_email
    msg["Date"] = email.utils.formatdate(localtime=True)

    errors = []

    # Method 1: If mail_cmd is explicitly passed
    if mail_cmd:
        try:
            cmd_name = os.path.basename(mail_cmd)
            if cmd_name in ("mail", "mailx"):
                proc = subprocess.run(
                    [mail_cmd, "-s", subject, to_email],
                    input=body,
                    text=True,
                    capture_output=True,
                    timeout=15,
                    check=False,
                )
            elif "sendmail" in cmd_name:
                proc = subprocess.run(
                    [mail_cmd, "-t", "-oi"],
                    input=msg.as_string(),
                    text=True,
                    capture_output=True,
                    timeout=15,
                    check=False,
                )
            else:
                proc = subprocess.run(
                    [mail_cmd, to_email],
                    input=body,
                    text=True,
                    capture_output=True,
                    timeout=15,
                    check=False,
                )

            if proc.returncode == 0:
                return True, f"Sent via command '{mail_cmd}'"
            err = proc.stderr.strip() or f"exit code {proc.returncode}"
            return False, f"Command '{mail_cmd}' failed: {err}"
        except Exception as e:
            return False, f"Failed executing '{mail_cmd}': {e}"

    # Method 2: If SMTP server is explicitly passed
    if smtp_server:
        port = smtp_port or (465 if smtp_ssl else (587 if smtp_tls else 25))
        password = smtp_password or os.environ.get("SMTP_PASSWORD", "")
        try:
            if smtp_ssl:
                server = smtplib.SMTP_SSL(smtp_server, port, timeout=15)
            else:
                server = smtplib.SMTP(smtp_server, port, timeout=15)

            if smtp_tls and not smtp_ssl:
                server.starttls()

            if smtp_user:
                server.login(smtp_user, password)

            server.send_message(msg)
            server.quit()
            return True, f"Sent via SMTP server {smtp_server}:{port}"
        except Exception as e:
            return False, f"SMTP delivery to {smtp_server}:{port} failed: {e}"

    # Method 3: Auto-detect local system tools (mailx / mail)
    for tool in ("mailx", "mail"):
        tool_path = shutil.which(tool)
        if tool_path:
            try:
                proc = subprocess.run(
                    [tool_path, "-s", subject, to_email],
                    input=body,
                    text=True,
                    capture_output=True,
                    timeout=15,
                    check=False,
                )
                if proc.returncode == 0:
                    return True, f"Sent via '{tool_path}'"
                errors.append(f"{tool} failed: {proc.stderr.strip()}")
            except Exception as e:
                errors.append(f"{tool} error: {e}")

    # Method 4: Auto-detect sendmail binary
    sendmail_paths = [
        shutil.which("sendmail"),
        "/usr/sbin/sendmail",
        "/usr/lib/sendmail",
    ]
    for s_path in sendmail_paths:
        if s_path and os.path.exists(s_path):
            try:
                proc = subprocess.run(
                    [s_path, "-t", "-oi"],
                    input=msg.as_string(),
                    text=True,
                    capture_output=True,
                    timeout=15,
                    check=False,
                )
                if proc.returncode == 0:
                    return True, f"Sent via '{s_path}'"
                errors.append(f"{s_path} failed: {proc.stderr.strip()}")
            except Exception as e:
                errors.append(f"{s_path} error: {e}")
            break

    # Method 5: Attempt localhost SMTP (127.0.0.1:25)
    try:
        server = smtplib.SMTP("127.0.0.1", 25, timeout=10)
        server.send_message(msg)
        server.quit()
        return True, "Sent via local SMTP relay (127.0.0.1:25)"
    except Exception as e:
        errors.append(f"Localhost SMTP (127.0.0.1:25) failed: {e}")

    summary = "; ".join(errors) if errors else "No mail utility or SMTP server found."
    return False, summary


def find_jobs_list(target_dir: Path) -> Path | None:
    """Searches target_dir and its parent for a jobs.list file."""
    candidates = [
        target_dir / "jobs.list",
        target_dir.parent / "jobs.list",
    ]
    for c in candidates:
        if c.is_file():
            return c
    return None


def count_jobs_in_list(jobs_list_path: Path) -> int:
    """Counts non-empty lines in a jobs.list file."""
    try:
        with jobs_list_path.open("r", encoding="utf-8", errors="ignore") as f:
            return sum(1 for line in f if line.strip())
    except Exception:
        return 0


def resolve_target_dir(raw_path: str, pattern: str) -> tuple[Path, str]:
    """
    Resolves target directory. If given directory has a 'stdout' subdirectory
    containing matching files, auto-resolves to 'stdout'.
    """
    p = Path(raw_path).expanduser().resolve()
    stdout_subdir = p / "stdout"
    if stdout_subdir.is_dir():
        # Fast check if parent directory itself contains matching files
        has_matches_in_parent = False
        try:
            with os.scandir(str(p)) as it:
                for entry in it:
                    if not entry.name.startswith(".") and fnmatch.fnmatch(entry.name, pattern) and entry.is_file():
                        has_matches_in_parent = True
                        break
        except OSError:
            pass

        if not has_matches_in_parent:
            return stdout_subdir, f"Resolved to subdirectory '{stdout_subdir}'"
    return p, ""


def inspect_log_file(
    file_path: str | Path,
    finish_regex: re.Pattern,
    error_regex: re.Pattern | None = None,
    max_bytes: int = 8192,
    size: int | None = None,
    finish_token: bytes | None = b"Finished",
) -> tuple[bool, str, str | None]:
    """
    Inspects the tail of a log file for finish message or errors.
    Optimized with fast byte-level pre-filtering and optional pre-computed file size.

    Returns:
        (is_finished: bool, status_desc: str, matched_line: str | None)
    """
    try:
        if size is None:
            size = os.path.getsize(file_path)

        if size == 0:
            return False, "File is empty (job starting)", None

        read_bytes = min(size, max_bytes)
        with open(file_path, "rb") as f:
            if size > read_bytes:
                f.seek(size - read_bytes)
            chunk = f.read(read_bytes)

        # Fast byte pre-filter:
        # Check if the finish token or any known error token is present in raw bytes.
        # This allows 99% of normal in-progress files to return instantly without line splitting or regex.
        has_finish = (finish_token is None) or (finish_token in chunk)
        has_error = (error_regex is not None) and any(token in chunk for token in ERROR_BYTE_TOKENS)

        if not has_finish and not has_error:
            return False, "In progress", None

        # Decode tail chunk only when a candidate token was detected
        text = chunk.decode("utf-8", errors="ignore")
        lines = [line.strip() for line in text.splitlines() if line.strip()]
        if not lines:
            return False, "No readable text", None

        # Check for finish message from the bottom up
        if has_finish:
            for line in reversed(lines):
                if finish_regex.search(line):
                    return True, "Finished", line

        # Check for known errors if not finished
        if has_error and error_regex:
            for line in reversed(lines):
                if error_regex.search(line):
                    return False, f"Failed: {line[:80]}", None

        return False, "In progress", None
    except Exception as e:
        return False, f"Read error: {e}", None


def generate_completion_report(
    target_dir: Path,
    start_time: datetime,
    check_count: int,
    total_files: int,
    completed_files: dict[str, str],
    failed_files: dict[str, str],
    finish_pattern_str: str,
    interval_sec: float,
    expected_jobs: int | None = None,
) -> str:
    """Builds a diagnostic completion report email."""
    now = datetime.now()
    duration_str = format_duration((now - start_time).total_seconds())
    hostname = socket.gethostname()
    try:
        fqdn = socket.getfqdn()
    except Exception:
        fqdn = hostname

    completed_count = len(completed_files)
    failed_count = len(failed_files)
    pct = (completed_count / total_files * 100.0) if total_files > 0 else 0.0

    if failed_count == 0 and completed_count == total_files:
        status_header = "ALL JOBS COMPLETED SUCCESSFULLY"
    elif failed_count > 0:
        status_header = f"COMPLETED WITH {failed_count} ERROR(S)"
    else:
        status_header = f"PARTIALLY COMPLETED ({completed_count}/{total_files})"

    # Sample completed files (up to 12)
    sample_completed = []
    for fname, match_line in list(completed_files.items())[:12]:
        sample_completed.append(f"  - {fname}: \"{match_line}\"")
    if len(completed_files) > 12:
        sample_completed.append(f"  ... and {len(completed_files) - 12} more completed files.")

    sample_completed_str = "\n".join(sample_completed) if sample_completed else "  (None)"

    # Failed files list (if any)
    failed_section = ""
    if failed_files:
        failed_lines = [f"  - {fname}: {err}" for fname, err in list(failed_files.items())[:15]]
        if len(failed_files) > 15:
            failed_lines.append(f"  ... and {len(failed_files) - 15} more failed files.")
        failed_section = f"""
Failed / Errored Jobs ({failed_count}):
----------------------------------------------------------------------
""" + "\n".join(failed_lines) + "\n"

    expected_info = f"Expected Jobs:       {expected_jobs}\n" if expected_jobs else ""

    report = f"""Hello,

This is an automated notification from {hostname}.

Status: {status_header}
Target Directory: {target_dir}

Execution Summary:
----------------------------------------------------------------------
Host:                {fqdn} ({hostname})
Directory:           {target_dir}
Total Files Found:   {total_files}
Finished Jobs:       {completed_count} ({pct:.1f}%)
Failed Jobs:         {failed_count}
{expected_info}Finish Pattern:      {finish_pattern_str}
Monitoring Started:  {start_time.strftime('%Y-%m-%d %H:%M:%S %Z')}
Completed At:        {now.strftime('%Y-%m-%d %H:%M:%S %Z')}
Total Wait Time:     {duration_str}
Checks Performed:    {check_count}
Check Interval:      {interval_sec:.1f}s

Sample Completed Files ({min(len(completed_files), 12)} shown):
----------------------------------------------------------------------
{sample_completed_str}
{failed_section}
----------------------------------------------------------------------
Notification generated by scripts/condor/monitor_jobs.py
"""
    return report


def build_parser() -> argparse.ArgumentParser:
    """Constructs and returns the command line argument parser."""
    parser = argparse.ArgumentParser(
        description="Monitor a directory of Condor Fun4All job output files until all finish, then notify via email.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  %(prog)s /sphenix/u/user/scratch/f4a/stdout 60 user@bnl.gov
  %(prog)s --dir scratch/f4a --interval 5m --email user@bnl.gov
  %(prog)s -d scratch/f4a/stdout -i 30s -e user@bnl.gov -n 120
  %(prog)s --test-email --email user@bnl.gov
  %(prog)s /sphenix/u/user/scratch/f4a/stdout --run-once
""",
    )

    # Positional arguments
    parser.add_argument(
        "pos_dir",
        nargs="?",
        default=None,
        metavar="DIR",
        help="Target directory containing job output files (e.g. stdout/ or submission dir)",
    )
    parser.add_argument(
        "pos_interval",
        nargs="?",
        default=None,
        metavar="INTERVAL",
        help="Polling interval, e.g. 60, 30s, 5m, 1h (default: 60s)",
    )
    parser.add_argument(
        "pos_email",
        nargs="?",
        default=None,
        metavar="EMAIL",
        help="Recipient email address to notify on completion (if not passed via --email)",
    )

    # Flag equivalents
    parser.add_argument("-d", "--dir", "--path", dest="flag_dir", default=None, metavar="DIR", help="Target directory to monitor")
    parser.add_argument("-i", "--interval", dest="flag_interval", default=None, metavar="INTERVAL", help="Polling interval (default: 60s)")
    parser.add_argument("-e", "--email", dest="flag_email", default=None, metavar="EMAIL", help="Recipient email address")
    parser.add_argument("-s", "--subject", default=None, help="Custom email subject")
    parser.add_argument(
        "-p",
        "--pattern",
        default="*.out",
        help="Glob pattern for log files in target directory (default: '*.out')",
    )
    parser.add_argument(
        "-m",
        "--finish-message",
        default=None,
        help="Custom finish message or regex pattern (default: 'Finished' or 'Finished successfully')",
    )
    parser.add_argument(
        "-n",
        "--expected-jobs",
        type=int,
        default=None,
        help="Expected total number of jobs (auto-detected from jobs.list if available)",
    )
    parser.add_argument(
        "--min-files",
        type=int,
        default=1,
        help="Minimum number of files required before checking completion (default: 1)",
    )
    parser.add_argument(
        "--tail-bytes",
        type=int,
        default=8192,
        help="Number of bytes from the tail of each log file to inspect (default: 8192)",
    )
    parser.add_argument(
        "-j",
        "--jobs",
        "--threads",
        dest="threads",
        type=int,
        default=16,
        help="Number of parallel worker threads for scanning log files (default: 16)",
    )
    parser.add_argument(
        "--notify-on-failure",
        action="store_true",
        help="Send email notification if all jobs finish running but some had errors",
    )
    parser.add_argument(
        "--test-email",
        action="store_true",
        help="Send a test email immediately to verify email settings, then exit",
    )
    parser.add_argument(
        "--run-once",
        action="store_true",
        help="Inspect directory once and report current job completion status, then exit",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Quiet mode: suppress periodic check log messages",
    )

    # Email configuration group
    mail_grp = parser.add_argument_group("Email / SMTP Configuration Options")
    mail_grp.add_argument(
        "--mail-cmd",
        default=None,
        help="Force specific local mail binary (e.g. 'mailx', 'mail', or '/usr/sbin/sendmail')",
    )
    mail_grp.add_argument(
        "--smtp-server",
        default=None,
        help="SMTP server hostname or IP (e.g. 'localhost', 'smtp.bnl.gov')",
    )
    mail_grp.add_argument(
        "--smtp-port",
        type=int,
        default=None,
        help="SMTP server port (defaults: 25 plain, 587 TLS, 465 SSL)",
    )
    mail_grp.add_argument("--smtp-user", default=None, help="SMTP username for authentication")
    mail_grp.add_argument(
        "--smtp-password",
        default=None,
        help="SMTP password (or set via SMTP_PASSWORD environment variable)",
    )
    mail_grp.add_argument("--smtp-tls", action="store_true", help="Use STARTTLS for SMTP")
    mail_grp.add_argument("--smtp-ssl", action="store_true", help="Use SSL/TLS for SMTP")
    mail_grp.add_argument("--sender", default=None, help="Sender email address (default: <user>@<hostname>)")

    return parser


def main() -> int:
    """Main CLI entry point for monitoring Condor Fun4All jobs."""
    parser = build_parser()
    args = parser.parse_args()

    # Resolve arguments (flags override positional)
    raw_dir = args.flag_dir or args.pos_dir
    raw_interval = args.flag_interval or args.pos_interval or "60s"
    email_addr = args.flag_email or args.pos_email

    mail_kwargs = {
        "sender": args.sender,
        "smtp_server": args.smtp_server,
        "smtp_port": args.smtp_port,
        "smtp_user": args.smtp_user,
        "smtp_password": args.smtp_password,
        "smtp_tls": args.smtp_tls,
        "smtp_ssl": args.smtp_ssl,
        "mail_cmd": args.mail_cmd,
    }

    # Handle test-email mode
    if args.test_email:
        if not email_addr:
            parser.error("Recipient email is required for --test-email. Specify via argument or --email.")
        print(f"Sending test email to {email_addr}...")
        test_subject = f"[Test] Condor Job Monitor Email Test from {socket.gethostname()}"
        test_body = (
            f"Hello,\n\n"
            f"This is a test notification from monitor_jobs.py on host {socket.gethostname()}.\n"
            f"If you received this message, your email configuration is working properly!\n\n"
            f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        )
        ok, msg = send_email(to_email=email_addr, subject=test_subject, body=test_body, **mail_kwargs)
        if ok:
            print(f"[SUCCESS] Test email sent successfully: {msg}")
            return 0
        print(f"[FAILED] Could not send test email: {msg}", file=sys.stderr)
        return 1

    # For monitoring or run-once, target directory is required
    if not raw_dir:
        parser.error("Target directory is required. Specify as first positional argument or via --dir.")

    # Parse interval
    try:
        interval = parse_interval(raw_interval)
        if interval <= 0:
            raise ValueError("Interval must be positive")
    except ValueError as e:
        parser.error(str(e))

    # For monitoring loop, recipient email is required
    if not args.run_once and not email_addr:
        parser.error("Recipient email is required. Specify as third positional argument or via --email.")

    # Compile regexes
    finish_pattern_str = args.finish_message or DEFAULT_FINISH_PATTERN
    try:
        finish_regex = re.compile(finish_pattern_str, re.IGNORECASE)
    except re.error as e:
        parser.error(f"Invalid finish-message regex '{finish_pattern_str}': {e}")

    error_regex = re.compile(DEFAULT_ERROR_PATTERN, re.IGNORECASE)

    # Pre-filter token for raw byte scanning
    finish_token: bytes | None = b"Finished"
    if args.finish_message:
        # If user passed custom finish regex, disable token pre-filter to guarantee regex correctness
        finish_token = None

    # Resolve target directory
    target_dir, resolve_note = resolve_target_dir(raw_dir, args.pattern)
    if resolve_note and not args.quiet:
        print(f"[INFO] {resolve_note}")

    # Detect expected jobs
    expected_jobs = args.expected_jobs
    jobs_list_file = find_jobs_list(target_dir)
    if expected_jobs is None and jobs_list_file:
        detected_count = count_jobs_in_list(jobs_list_file)
        if detected_count > 0:
            expected_jobs = detected_count
            if not args.quiet:
                print(f"[INFO] Auto-detected {expected_jobs} expected jobs from '{jobs_list_file}'")

    start_time = datetime.now()
    hostname = socket.gethostname()
    threads = max(1, args.threads)

    # Cache across checks
    completed_files: dict[str, str] = {}              # filename -> matched line
    failed_files: dict[str, str] = {}                 # filename -> error desc
    file_stat_cache: dict[str, tuple[int, int]] = {}  # filename -> (size, mtime_ns)

    # Optimize pattern matching: check if pattern is simple suffix like '*.out'
    is_suffix_pattern = args.pattern.startswith("*.") and "*" not in args.pattern[2:] and "?" not in args.pattern
    pattern_suffix = args.pattern[1:] if is_suffix_pattern else None

    def scan_directory(executor: ThreadPoolExecutor) -> tuple[int, int, int]:
        """
        Scans target_dir using os.scandir, mtime/size caching, and ThreadPoolExecutor.
        Returns:
            (total_count, done_count, in_prog_count)
        """
        target_dir_str = str(target_dir)
        if not os.path.isdir(target_dir_str):
            return 0, 0, 0

        entries_to_inspect = []
        matching_count = 0
        all_regular_count = 0

        try:
            with os.scandir(target_dir_str) as it:
                for entry in it:
                    name = entry.name
                    if name.startswith("."):
                        continue

                    matched = name.endswith(pattern_suffix) if pattern_suffix else fnmatch.fnmatch(name, args.pattern)

                    try:
                        if not entry.is_file():
                            continue
                    except OSError:
                        continue

                    all_regular_count += 1
                    if not matched:
                        continue

                    matching_count += 1
                    if name in completed_files:
                        continue

                    try:
                        st = entry.stat()
                        size = st.st_size
                        mtime_ns = st.st_mtime_ns
                    except OSError:
                        continue

                    current_stat = (size, mtime_ns)
                    prev_stat = file_stat_cache.get(name)

                    if prev_stat == current_stat:
                        # File has not changed since last check; status is unchanged
                        continue

                    if size == 0:
                        # 0-byte file: definitely empty/starting, record in cache and skip
                        file_stat_cache[name] = current_stat
                        continue

                    entries_to_inspect.append((entry.path, name, size, current_stat))
        except OSError as e:
            if not args.quiet:
                print(f"[WARNING] Could not scan directory {target_dir}: {e}", file=sys.stderr)
            return 0, len(completed_files), 0

        # Fallback: if no files matched pattern and pattern was default '*.out', check regular files
        if matching_count == 0 and args.pattern == "*.out" and all_regular_count > 0:
            try:
                with os.scandir(target_dir_str) as it:
                    for entry in it:
                        name = entry.name
                        if name.startswith("."):
                            continue
                        try:
                            if not entry.is_file():
                                continue
                            matching_count += 1
                            if name in completed_files:
                                continue
                            st = entry.stat()
                            size = st.st_size
                            mtime_ns = st.st_mtime_ns
                            current_stat = (size, mtime_ns)
                            if file_stat_cache.get(name) == current_stat:
                                continue
                            if size == 0:
                                file_stat_cache[name] = current_stat
                                continue
                            entries_to_inspect.append((entry.path, name, size, current_stat))
                        except OSError:
                            continue
            except OSError:
                pass

        # Inspect pending files in parallel
        if entries_to_inspect:
            def _worker(item):
                fpath, fname, fsize, fstat = item
                is_done, status, match_str = inspect_log_file(
                    fpath,
                    finish_regex=finish_regex,
                    error_regex=error_regex,
                    max_bytes=args.tail_bytes,
                    size=fsize,
                    finish_token=finish_token,
                )
                return fname, fstat, is_done, status, match_str

            if len(entries_to_inspect) == 1:
                results = [_worker(entries_to_inspect[0])]
            else:
                chunk_sz = min(128, max(1, len(entries_to_inspect) // (threads * 4)))
                results = executor.map(_worker, entries_to_inspect, chunksize=chunk_sz)

            for fname, fstat, is_done, status, match_str in results:
                file_stat_cache[fname] = fstat
                if is_done:
                    completed_files[fname] = match_str or "Finished"
                    failed_files.pop(fname, None)
                elif status.startswith("Failed:"):
                    failed_files[fname] = status
                else:
                    failed_files.pop(fname, None)

        total = max(matching_count, len(completed_files) + len(failed_files))
        done = len(completed_files)
        errs = len(failed_files)
        in_prog = max(0, total - done - errs)
        return total, done, in_prog

    executor = ThreadPoolExecutor(max_workers=threads)
    try:
        # Run-once mode
        if args.run_once:
            print(f"Scanning target directory: {target_dir}")
            print(f"Pattern: '{args.pattern}' | Finish Regex: '{finish_pattern_str}' | Threads: {threads}")
            total, done, in_prog = scan_directory(executor)

            print("=" * 70)
            print(f"Total files found:  {total}")
            if expected_jobs:
                print(f"Expected jobs:      {expected_jobs}")
            print(f"Completed jobs:     {done} ({(done / total * 100.0 if total > 0 else 0.0):.1f}%)")
            print(f"In-progress jobs:   {in_prog}")
            print(f"Failed jobs:        {len(failed_files)}")
            print("=" * 70)

            if failed_files:
                print("\nFailed jobs detected:")
                for fn, err in list(failed_files.items())[:10]:
                    print(f"  - {fn}: {err}")
                if len(failed_files) > 10:
                    print(f"  ... and {len(failed_files) - 10} more.")

            all_done = (done == total) and (total >= (expected_jobs or args.min_files)) and (total > 0)
            if all_done:
                print("[STATUS] ALL JOBS COMPLETED SUCCESSFULLY!")
                return 0
            print("[STATUS] Incomplete / pending jobs remaining.")
            return 1

        # Standard monitoring loop
        print("=" * 70)
        print("CONDOR FUN4ALL JOB COMPLETION MONITOR")
        print("=" * 70)
        print(f"  Target Dir:     {target_dir}")
        print(f"  File Pattern:   {args.pattern}")
        print(f"  Finish Pattern: {finish_pattern_str}")
        if expected_jobs:
            print(f"  Expected Jobs:  {expected_jobs}" + (" (from jobs.list)" if jobs_list_file else ""))
        print(f"  Interval:       {interval:.1f}s ({raw_interval})")
        print(f"  Threads:        {threads}")
        print(f"  Notification:   {email_addr}")
        print(f"  Host:           {hostname}")
        print(f"  Started:        {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
        print("=" * 70)

        check_count = 0
        while True:
            check_count += 1
            now = datetime.now()
            elapsed_str = format_duration((now - start_time).total_seconds())

            if not target_dir.is_dir():
                if not args.quiet:
                    print(f"[{now.strftime('%H:%M:%S')}] Check #{check_count} (Elapsed: {elapsed_str}): Directory does not exist yet ({target_dir}). Waiting...")
                time.sleep(interval)
                continue

            total, done, in_prog = scan_directory(executor)

            # Check if expected files threshold is met
            threshold = expected_jobs if expected_jobs is not None else args.min_files

            if total == 0:
                if not args.quiet:
                    print(f"[{now.strftime('%H:%M:%S')}] Check #{check_count} (Elapsed: {elapsed_str}): No matching files found in {target_dir}. Waiting for jobs to produce output...")
                time.sleep(interval)
                continue

            pct = (done / total * 100.0) if total > 0 else 0.0
            fail_count = len(failed_files)

            # Check completion condition: all files in dir have the finish message
            if done == total and total >= threshold:
                print("\n" + "=" * 70)
                print(f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] SUCCESS: All {done}/{total} jobs have completed successfully!")
                print(f"All files in '{target_dir}' contain the finish message.")
                print("=" * 70)

                subject = args.subject or f"[Done] All {done} Condor Jobs Completed on {hostname} ({target_dir.name})"
                body = generate_completion_report(
                    target_dir=target_dir,
                    start_time=start_time,
                    check_count=check_count,
                    total_files=total,
                    completed_files=completed_files,
                    failed_files=failed_files,
                    finish_pattern_str=finish_pattern_str,
                    interval_sec=interval,
                    expected_jobs=expected_jobs,
                )

                print(f"Sending notification email to {email_addr}...")
                ok, msg = send_email(to_email=email_addr, subject=subject, body=body, **mail_kwargs)
                if ok:
                    print(f"[SUCCESS] Email delivered successfully: {msg}")
                else:
                    print(f"[WARNING] Failed to deliver email: {msg}", file=sys.stderr)
                    print("=" * 70)
                    print("Report content was:")
                    print(body)
                    print("=" * 70)

                print("Task complete. Exiting.")
                return 0

            # Check terminal state with failures if requested
            if args.notify_on_failure and (done + fail_count == total) and total >= threshold and fail_count > 0:
                print("\n" + "=" * 70)
                print(f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] ALL JOBS FINISHED with {fail_count} failure(s) ({done}/{total} succeeded).")
                print("=" * 70)

                subject = args.subject or f"[Alert] Condor Jobs Finished with Errors on {hostname} ({target_dir.name})"
                body = generate_completion_report(
                    target_dir=target_dir,
                    start_time=start_time,
                    check_count=check_count,
                    total_files=total,
                    completed_files=completed_files,
                    failed_files=failed_files,
                    finish_pattern_str=finish_pattern_str,
                    interval_sec=interval,
                    expected_jobs=expected_jobs,
                )

                print(f"Sending failure notification email to {email_addr}...")
                ok, msg = send_email(to_email=email_addr, subject=subject, body=body, **mail_kwargs)
                if ok:
                    print(f"[SUCCESS] Email delivered successfully: {msg}")
                else:
                    print(f"[WARNING] Failed to deliver email: {msg}", file=sys.stderr)

                return 1

            # Ongoing progress
            if not args.quiet:
                status_parts = [f"{done}/{total} finished ({pct:.1f}%)"]
                if in_prog > 0:
                    status_parts.append(f"{in_prog} in progress")
                if fail_count > 0:
                    status_parts.append(f"{fail_count} failed")
                if expected_jobs and total < expected_jobs:
                    status_parts.append(f"waiting for {expected_jobs - total} more output files")

                status_line = ", ".join(status_parts)
                print(f"[{now.strftime('%H:%M:%S')}] Check #{check_count} (Elapsed: {elapsed_str}): {status_line}")

            time.sleep(interval)

    except KeyboardInterrupt:
        total_time = format_duration((datetime.now() - start_time).total_seconds())
        print(f"\nMonitoring stopped by user after {check_count} checks ({total_time}). Exiting.")
        return 130
    finally:
        executor.shutdown(wait=False, cancel_futures=True)


if __name__ == "__main__":
    sys.exit(main())
